In [18]:
import sys
# sys.path.append('/Users/bernardoloureiro/template-lib')

from utils.notebookhelpers.helpers import Helpers
from utils.dtos.templateOutputCollection import TemplateOutputCollection
from utils.dtos.variable import Metadata
from utils.dtos.templateOutput import TemplateOutput
from utils.dtos.templateOutput import OutputType
from utils.dtos.templateOutput import ChartType
import logging
import os
from dateutil import parser
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)
# pd.set_option('display.max_rows', 5000)
# pd.set_option('display.max_columns', 5000)
# pd.set_option('display.width', 1000)

# import matplotlib.pyplot as plt
# import seaborn as sns
# !pip install networkx
# %matplotlib inline
import pandas as pd
import copy
import numpy as np
import networkx as nx
# !pip install scipy
# from scipy import stats
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

In [44]:
#Getting the context
contextId = 'Airline_cargo'
context = Helpers.getOrCreateContext(contextId=contextId, localVars=locals())


inputDatasetParameter = Helpers.get_or_create_input_dataset(
    name="inputDataset",
    metadata=Metadata(input_name='Input Dataset', is_required=True, tooltip='Dataset to apply the transformation'),
    local_context=locals())




Month_Parameter = Helpers.get_or_create_input_var(name="Month",
    metadata=Metadata(input_name="Month", is_required=True, tooltip="All Airline names", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
    )

AustralianPort_Parameter = Helpers.get_or_create_input_var(
    name="AustralianPort",
    metadata=Metadata(input_name="AustralianPort", is_required=True, tooltip="AustralianPort", multiple=False,datatypes=['STRING'] ,options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


ForeignPort_Parameter = Helpers.get_or_create_input_var(
    name="ForeignPort",
    metadata=Metadata(input_name="ForeignPort", is_required=True, tooltip="ForeignPort", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Country_Parameter = Helpers.get_or_create_input_var(
    name="Country",
    metadata=Metadata(input_name="Country", is_required=True, tooltip="Country", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Passengers_In_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_In",
    metadata=Metadata(input_name="Passengers_In", is_required=True, tooltip="All Passengers_In", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

# Airline_Parameter = Helpers.get_or_create_input_var(
#     name="Airline",
#     metadata=Metadata(input_name="Sectors_Flown", is_required=True, tooltip="All Departures_On_Time", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
#     local_context=locals()
# )



Freight_In_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_In_tonnes",
    metadata=Metadata(input_name="Freight_In_tonnes", is_required=True, tooltip="Freight_In_(tonnes)", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Mail_In_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_In_tonnes",
    metadata=Metadata(input_name="Mail_In_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Passengers_Out_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_Out",
    metadata=Metadata(input_name="Passengers_Out", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

# useless_Parameter = Helpers.get_or_create_input_var(
#     name="useless",
#     metadata=Metadata(input_name="Departing_Port", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
#     local_context=locals()
# )



Freight_Out_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_Out_tonnes",
    metadata=Metadata(input_name="Freight_Out_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Mail_Out_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_Out_tonnes",
    metadata=Metadata(input_name="Mail_Out_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Passengers_Total_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_Total",
    metadata=Metadata(input_name="Passengers_Total", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Freight_Total_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_Total_tonnes",
    metadata=Metadata(input_name="Freight_Total_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Mail_Total_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_Total_tonnes",
    metadata=Metadata(input_name="Mail_Total_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Year_Parameter = Helpers.get_or_create_input_var(
    name="Year",
    metadata=Metadata(input_name="Year", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Month_num_Parameter = Helpers.get_or_create_input_var(
    name="Month_num",
    metadata=Metadata(input_name="Month_num", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)




Btwness_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Btwness",
    metadata=Metadata(input_name="Btwness", is_required=True, tooltip="Output column", multiple=False,
),
    local_context=locals()
)


closeness_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="closeness",
    metadata=Metadata(input_name="closeness", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


Deg_centrality_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Deg_centrality",
    metadata=Metadata(input_name="Deg_centrality", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Freight_In_Out_prct_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Freight_In_Out_prct",
    metadata=Metadata(input_name="Freight_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 



Passengers_In_Out_prct_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Passengers_In_Out_prct",
    metadata=Metadata(input_name="Passengers_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


Mail_In_Out_prct_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Mail_In_Out_prct",
    metadata=Metadata(input_name="Mail_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 



W_Passengers_In_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="W_Passengers_In",
    metadata=Metadata(input_name="W_Passengers_In", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


W_Passengers_Out_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="W_Passengers_Out",
    metadata=Metadata(input_name="W_Passengers_Out", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


W_Passengers_Total_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="W_Passengers_Total",
    metadata=Metadata(input_name="W_Passengers_Total", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


flights_total_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="flights_total",
    metadata=Metadata(input_name="flights_total", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Total_wt_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Total_wt",
    metadata=Metadata(input_name="Total_wt", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Avg_flight_wt_outputcolumnParameter = Helpers.get_or_create_input_var(
    name="Avg_flight_wt",
    metadata=Metadata(input_name="Avg_flight_wt", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 






outputDataset_Parameter =Helpers.get_or_create_output_dataset(
 name="outputDataset",
    metadata=Metadata(input_name='outputDataset', is_required=True, tooltip='Dataset name to be created after the transformation'),
    local_context=locals()
)

In [45]:
#Getting the parameters
airline=inputDatasetParameter.value

outputDataset=outputDataset_Parameter.value

Month = Month_Parameter.value

AustralianPort =AustralianPort_Parameter.value
ForeignPort =    ForeignPort_Parameter.value
Country =    Country_Parameter.value
Passengers_In=    Passengers_In_Parameter.value
Freight_In_tonnes=    Freight_In_tonnes_Parameter.value
Mail_In_tonnes = Mail_In_tonnes_Parameter.value
Passengers_Out = Passengers_Out_Parameter.value


Freight_Out_tonnes = Freight_Out_tonnes_Parameter.value
Mail_Out_tonnes=Mail_Out_tonnes_Parameter.value
Freight_Total_tonnes =  Freight_Total_tonnes_Parameter.value

Passengers_Total = Passengers_Total_Parameter.value
Mail_Total_tonnes = Mail_Total_tonnes_Parameter.value
Year=Year_Parameter.value

Month_num = Month_num_Parameter.value


Btwness = Btwness_outputcolumnParameter.value
closeness = closeness_outputcolumnParameter.value
Deg_centrality = Deg_centrality_outputcolumnParameter.value

Freight_In_Out_prct =     Freight_In_Out_prct_outputcolumnParameter.value
Passengers_In_Out_prct=    Passengers_In_Out_prct_outputcolumnParameter.value
Mail_In_Out_prct =    Mail_In_Out_prct_outputcolumnParameter.value
W_Passengers_In=    W_Passengers_In_outputcolumnParameter.value
W_Passengers_Out =    W_Passengers_Out_outputcolumnParameter.value
W_Passengers_Total =    W_Passengers_Total_outputcolumnParameter.value
flights_total=    flights_total_outputcolumnParameter.value
Total_wt =    Total_wt_outputcolumnParameter.value
Avg_flight_wt =    Avg_flight_wt_outputcolumnParameter.value





# outputDataset2=outputDatasetParameter2.value

In [46]:
inputDatasetParameter

Variable(name='inputDataset', metadata=Metadata(input_name='Input Dataset', is_required=True, tooltip='Dataset to apply the transformation', default_value=None, multiple=None, output=None, datatypes=None, options=None, constant_options=None, datatype=None, datasets=None, dataset=None, input_dataset=True, output_dataset=None, output_chart=None))

In [47]:
airline = Helpers.getEntityData(context, airline)

In [48]:
airline.head(2)

,Month,AustralianPort,ForeignPort,Country,Passengers_In,Freight_In_tonnes,Mail_In_tonnes,Passengers_Out,Freight_Out_tonnes,Mail_Out_tonnes,Passengers_Total,Freight_Total_tonnes,Mail_Total_tonnes,Year,Month_num
59569,Jan-09,Melbourne,Dubai,United Arab Emirates,14131,264.871,48.628,13201,548.965,0.000,27332,813.836,48.628,2009,1
30225,Mar-97,Perth,Vancouver,Canada,0,0.000,0.000,1,0.000,0.922,1,0.000,0.922,1997,3

In [49]:
#creating  betweenness centrality
routs = airline.groupby([AustralianPort,ForeignPort]).size().reset_index(name='count')
g = nx.from_pandas_edgelist(routs, source=AustralianPort, target=ForeignPort)
Btwnessv = pd.DataFrame(pd.DataFrame([nx.betweenness_centrality(g)]).unstack())
Btwnessv = Btwnessv.reset_index().rename(columns = { 'level_0': AustralianPort, 'level_1':'useless',
                                                  0:Btwness}).drop('useless',axis=1)
airline = Btwnessv.merge(airline,on=AustralianPort,how='inner')


#creating   closeness centrality
g = nx.from_pandas_edgelist(routs, source=AustralianPort, target=ForeignPort)
closenessv = pd.DataFrame(pd.DataFrame([nx.closeness_centrality(g)]).unstack())
closenessv = closenessv.reset_index().rename(columns = { 'level_0': AustralianPort, 'level_1':'useless',
                                                  0:closeness}).drop('useless',axis=1)
airline = closenessv.merge(airline,on=AustralianPort,how='inner')



#creating   degree centrality
g = nx.from_pandas_edgelist(routs, source=AustralianPort, target=ForeignPort)
Deg_centralityv = pd.DataFrame(pd.DataFrame([nx.degree_centrality(g)]).unstack())
Deg_centralityv = Deg_centralityv.reset_index().rename(columns = { 'level_0': AustralianPort, 'level_1':'useless',
                                                  0:Deg_centrality}).drop('useless',axis=1)
airline = Deg_centralityv.merge(airline,on=AustralianPort,how='inner')






airline[Freight_In_Out_prct] = (airline[Freight_In_tonnes] - airline[Freight_In_tonnes])/(1+airline[Freight_In_tonnes])
airline[Passengers_In_Out_prct] = (airline[Passengers_In] - airline[Passengers_Out])/(1+airline[Passengers_In])
# airline['Passengers_Total_Inside'] = (airline['Passengers_In'] - airline['Passengers_Out'])

airline[Mail_In_Out_prct] = (airline[Mail_In_tonnes] - airline[Mail_Out_tonnes])/(1+airline[Mail_Total_tonnes])



airline[W_Passengers_In] = airline[Passengers_In] *68/1000

airline[W_Passengers_Out] = airline[Passengers_Out] *68/1000
airline[W_Passengers_Total] = airline[Passengers_Total] *68/1000

# airline['W_Passengers_Total_Inside'] = airline['Passengers_Total_Inside'] *64/1000
airline[flights_total] = airline[Passengers_Total]/450
airline[Total_wt] = airline[flights_total] * (airline[Passengers_Total] *68/1000 + airline[Freight_Total_tonnes]+ airline[Mail_Total_tonnes])
airline[Avg_flight_wt] = (airline[Passengers_Total] *68/1000 + airline[Freight_Total_tonnes]+ airline[Mail_Total_tonnes])/(1+airline[flights_total])

# airline['flights'] = airline['Passengers_Total']/250
# airline['flightst_total'] = airline['Passengers_Total']/250

In [50]:
# Dropping all total zero rows data
all_zero = airline[(airline[Freight_Total_tonnes]  == 0) & (airline[Passengers_Total]  == 0) & (airline[Mail_Total_tonnes]  == 0)].index
airline = airline.drop(all_zero)

In [51]:
airline.head()

,AustralianPort,Deg_centrality,closeness,Btwness,Month,ForeignPort,Country,Passengers_In,Freight_In_tonnes,Mail_In_tonnes,...,Month_num,Freight_In_Out_prct,Passengers_In_Out_prct,Mail_In_Out_prct,W_Passengers_In,W_Passengers_Out,W_Passengers_Total,flights_total,Total_wt,Avg_flight_wt
0,Adelaide,0.325359,0.44186,0.02568,Aug-18,Singapore,Singapore,8021,281.184,0.0,...,8,0.0,0.120045,0.000000,545.428,479.944,1025.372,33.508889,53943.313020,46.649459
1,Adelaide,0.325359,0.44186,0.02568,Sep-96,Manila,Philippines,4,0.000,0.0,...,9,0.0,0.400000,0.000000,0.272,0.136,0.408,0.013333,0.005440,0.402632
2,Adelaide,0.325359,0.44186,0.02568,Jan-95,Frankfurt,Germany,117,1.912,0.0,...,1,0.0,-0.313559,-0.104745,7.956,10.472,18.428,0.602222,12.491293,12.945770
3,Adelaide,0.325359,0.44186,0.02568,Dec-88,Tokyo,Japan,0,0.000,0.0,...,12,0.0,-2.000000,0.000000,0.000,0.136,0.136,0.004444,0.000604,0.135398
4,Adelaide,0.325359,0.44186,0.02568,Sep-01,Johannesburg,South Africa,0,1.991,0.0,...,9,0.0,0.000000,-0.118943,0.000,0.000,0.000,0.000000,0.000000,2.463000

In [52]:
airline_grp = airline.groupby([AustralianPort,ForeignPort,Month_num]).agg({Deg_centrality:'mean',closeness:'mean',Btwness:'mean',
                                                                       Passengers_In:'sum',Freight_In_tonnes:'sum',
                                                                      Mail_In_tonnes:'sum',Passengers_Out:'sum',
                                                                      Freight_Out_tonnes:'sum',Mail_Out_tonnes:'sum',Passengers_Total:'sum',
                                                                     Mail_Total_tonnes:'sum' ,Freight_Total_tonnes:'sum',Freight_In_Out_prct:'mean',Passengers_In_Out_prct:'mean',
                                                                      Mail_In_Out_prct:'mean',W_Passengers_In:'sum',
                                                                      W_Passengers_Out:'sum',W_Passengers_Total:'sum',
                                                                     flights_total:'sum',Total_wt:'sum',Avg_flight_wt:'mean'}).reset_index(drop=True)
# k = airline_grp.copy()

k = airline_grp.reset_index(drop=True).copy()
# IQR
Q1 = np.percentile(k[Passengers_Total], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Passengers_Total], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Passengers_Total] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Passengers_Total] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

k = k.reset_index(drop=True)# IQR
Q1 = np.percentile(k[Mail_Total_tonnes], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Mail_Total_tonnes], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Mail_Total_tonnes] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Mail_Total_tonnes] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

k = k.reset_index(drop=True)# IQR
Q1 = np.percentile(k[Deg_centrality], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Deg_centrality], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Deg_centrality] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Deg_centrality] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

In [ ]:
airline = airline_grp.copy()

In [53]:
airline.head()

,Deg_centrality,closeness,Btwness,Passengers_In,Freight_In_tonnes,Mail_In_tonnes,Passengers_Out,Freight_Out_tonnes,Mail_Out_tonnes,Passengers_Total,...,Freight_Total_tonnes,Freight_In_Out_prct,Passengers_In_Out_prct,Mail_In_Out_prct,W_Passengers_In,W_Passengers_Out,W_Passengers_Total,flights_total,Total_wt,Avg_flight_wt
0,0.325359,0.44186,0.02568,6,0.0,0.0,16,18.7,0.0,22,...,18.7,0.0,-2.444444,0.0,0.408,1.088,1.496,0.048889,0.324436,6.625618
1,0.325359,0.44186,0.02568,13,0.0,0.0,7,23.9,0.0,20,...,23.9,0.0,-1.466667,0.0,0.884,0.476,1.360,0.044444,0.347858,8.305657
2,0.325359,0.44186,0.02568,10,0.0,0.0,4,17.7,0.0,14,...,17.7,0.0,0.019048,0.0,0.680,0.272,0.952,0.031111,0.052329,6.199981
3,0.325359,0.44186,0.02568,13,0.0,0.0,4,0.0,0.0,17,...,0.0,0.0,0.583333,0.0,0.884,0.272,1.156,0.037778,0.027049,0.376559
4,0.325359,0.44186,0.02568,25,0.9,0.0,4,14.3,0.0,29,...,15.2,0.0,0.388889,0.0,1.700,0.272,1.972,0.064444,0.255964,5.640034

In [ ]:
# airline = airline_grp.copy()

In [ ]:
outputCollection = Helpers.createOutputCollection(context)
# out = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=All_airline)
out = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=airline)
# out2 = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=All_airline)

outputCollection.addTemplateOutput(out)
Helpers.save(context)