In [20]:
import sys
# sys.path.append('/Users/bernardoloureiro/template-lib')

from utils.notebookhelpers.helpers import Helpers
from utils.dtos.templateOutputCollection import TemplateOutputCollection
from utils.dtos.variable import Metadata
from utils.dtos.templateOutput import TemplateOutput
from utils.dtos.templateOutput import OutputType
from utils.dtos.templateOutput import ChartType
import logging
import os
from dateutil import parser
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)
# pd.set_option('display.max_rows', 5000)
# pd.set_option('display.max_columns', 5000)
# pd.set_option('display.width', 1000)

# import matplotlib.pyplot as plt
# import seaborn as sns
# !pip install networkx
# %matplotlib inline
import pandas as pd
import copy
pd.set_option('display.max_rows', 500000)
pd.set_option('display.max_columns', 50000)
pd.set_option('display.width', 10000)
import numpy as np
# import networkx as nx
# !pip install scipy
# from scipy import stats
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

In [5]:
#Getting the context
contextId = 'Airline_cargo'
context = Helpers.getOrCreateContext(contextId=contextId, localVars=locals())


inputDatasetParameter = Helpers.get_or_create_input_dataset(
    name="inputDataset2",
    metadata=Metadata(input_name='Input Dataset', is_required=True, tooltip='Dataset to apply the transformation'),
    local_context=locals())



Passengers_In_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_In",
    metadata=Metadata(input_name="Passengers_In", is_required=True, tooltip="All Passengers_In", multiple=False, datatypes=['STRING'],options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Freight_In_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_In_tonnes",
    metadata=Metadata(input_name="Freight_In_tonnes", is_required=True, tooltip="Freight_In_(tonnes)", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Mail_In_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_In_tonnes",
    metadata=Metadata(input_name="Mail_In_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)


Passengers_Out_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_Out",
    metadata=Metadata(input_name="Passengers_Out", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Freight_Out_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_Out_tonnes",
    metadata=Metadata(input_name="Freight_Out_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Mail_Out_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_Out_tonnes",
    metadata=Metadata(input_name="Mail_Out_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)

Passengers_Total_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_Total",
    metadata=Metadata(input_name="Passengers_Total", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Freight_Total_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Freight_Total_tonnes",
    metadata=Metadata(input_name="Freight_Total_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)



Mail_Total_tonnes_Parameter = Helpers.get_or_create_input_var(
    name="Mail_Total_tonnes",
    metadata=Metadata(input_name="Mail_Total_tonnes", is_required=True, tooltip="All Departures_On_Time", multiple=False, options=['FIELDS', 'CONSTANT'], datasets=['inputDataset']),
    local_context=locals()
)




Btwness_Parameter = Helpers.get_or_create_input_var(
    name="Btwness",
    metadata=Metadata(input_name="Btwness", is_required=True, tooltip="Output column", multiple=False,
),
    local_context=locals()
)


closeness_Parameter = Helpers.get_or_create_input_var(
    name="closeness",
    metadata=Metadata(input_name="closeness", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


Deg_centrality_Parameter = Helpers.get_or_create_input_var(
    name="Deg_centrality",
    metadata=Metadata(input_name="Deg_centrality", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Freight_In_Out_prct_Parameter = Helpers.get_or_create_input_var(
    name="Freight_In_Out_prct",
    metadata=Metadata(input_name="Freight_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 



Passengers_In_Out_prct_Parameter = Helpers.get_or_create_input_var(
    name="Passengers_In_Out_prct",
    metadata=Metadata(input_name="Passengers_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


Mail_In_Out_prct_Parameter = Helpers.get_or_create_input_var(
    name="Mail_In_Out_prct",
    metadata=Metadata(input_name="Mail_In_Out_prct", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 



W_Passengers_In_Parameter = Helpers.get_or_create_input_var(
    name="W_Passengers_In",
    metadata=Metadata(input_name="W_Passengers_In", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


W_Passengers_Out_Parameter = Helpers.get_or_create_input_var(
    name="W_Passengers_Out",
    metadata=Metadata(input_name="W_Passengers_Out", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


W_Passengers_Total_Parameter = Helpers.get_or_create_input_var(
    name="W_Passengers_Total",
    metadata=Metadata(input_name="W_Passengers_Total", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 


flights_total_Parameter = Helpers.get_or_create_input_var(
    name="flights_total",
    metadata=Metadata(input_name="flights_total", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Total_wt_Parameter = Helpers.get_or_create_input_var(
    name="Total_wt",
    metadata=Metadata(input_name="Total_wt", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 

Avg_flight_wt_Parameter = Helpers.get_or_create_input_var(
    name="Avg_flight_wt",
    metadata=Metadata(input_name="Avg_flight_wt", is_required=True, tooltip="Output column", multiple=False, 
),
    local_context=locals()
) 






outputDataset_Parameter =Helpers.get_or_create_output_dataset(
 name="outputDataset2",
    metadata=Metadata(input_name='outputDataset', is_required=True, tooltip='Dataset name to be created after the transformation'),
    local_context=locals()
)

In [6]:
#Getting the parameters
airline_grp=inputDatasetParameter.value

outputDataset=outputDataset_Parameter.value

Passengers_In=    Passengers_In_Parameter.value
Freight_In_tonnes=    Freight_In_tonnes_Parameter.value
Mail_In_tonnes = Mail_In_tonnes_Parameter.value
Passengers_Out = Passengers_Out_Parameter.value


Freight_Out_tonnes = Freight_Out_tonnes_Parameter.value
Mail_Out_tonnes=Mail_Out_tonnes_Parameter.value
Freight_Total_tonnes =  Freight_Total_tonnes_Parameter.value

Passengers_Total = Passengers_Total_Parameter.value
Mail_Total_tonnes = Mail_Total_tonnes_Parameter.value

Btwness = Btwness_Parameter.value
closeness = closeness_Parameter.value
Deg_centrality = Deg_centrality_Parameter.value

Freight_In_Out_prct =     Freight_In_Out_prct_Parameter.value
Passengers_In_Out_prct=    Passengers_In_Out_prct_Parameter.value
Mail_In_Out_prct =    Mail_In_Out_prct_Parameter.value
W_Passengers_In=    W_Passengers_In_Parameter.value
W_Passengers_Out =    W_Passengers_Out_Parameter.value
W_Passengers_Total =    W_Passengers_Total_Parameter.value
flights_total=    flights_total_Parameter.value
Total_wt =    Total_wt_Parameter.value
Avg_flight_wt =    Avg_flight_wt_Parameter.value





# outputDataset2=outputDatasetParameter2.value

In [7]:
airline_grp = Helpers.getEntityData(context, airline_grp)

In [51]:
k =airline_grp.copy()

In [52]:
len(k)

6820

In [53]:
k = airline_grp.reset_index(drop=True).copy()
# IQR
Q1 = np.percentile(k[Passengers_Total], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Passengers_Total], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Passengers_Total] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Passengers_Total] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

Old Shape:  (6820, 21)
New Shape:  (5631, 21)

In [54]:
k = k.reset_index(drop=True)# IQR
Q1 = np.percentile(k[Mail_Total_tonnes], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Mail_Total_tonnes], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Mail_Total_tonnes] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Mail_Total_tonnes] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

Old Shape:  (5631, 21)
New Shape:  (4493, 21)

In [55]:
k = k.reset_index(drop=True)# IQR
Q1 = np.percentile(k[Deg_centrality], 25,
                   interpolation = 'midpoint')
 
Q3 = np.percentile(k[Deg_centrality], 75,
                   interpolation = 'midpoint')
IQR = Q3 - Q1
 
print("Old Shape: ", k.shape)
 
# Upper bound
upper = np.where(k[Deg_centrality] >= (Q3+1.5*IQR))
# Lower bound
lower = np.where(k[Deg_centrality] <= (Q1-1.5*IQR))
''' Removing the Outliers '''
k.drop(upper[0], inplace = True)
k.drop(lower[0], inplace = True)
 
print("New Shape: ", k.shape)

Old Shape:  (4493, 21)
New Shape:  (4493, 21)

In [64]:
len(k),k.shape

(4493, (4493, 21))

In [50]:
k.head(5)

   Deg_centrality  closeness  Btwness  Passengers_In  Freight_In_tonnes  Mail_In_tonnes  Passengers_Out  Freight_Out_tonnes  Mail_Out_tonnes  Passengers_Total  Mail_Total_tonnes  Freight_In_Out_prct  Passengers_In_Out_prct  Mail_In_Out_prct  W_Passengers_In  W_Passengers_Out  W_Passengers_Total  flights_total  Total_wt  Avg_flight_wt  Freight_Total_tonnes
0        0.325359    0.44186  0.02568              6                0.0             0.0              16                18.7              0.0                22                0.0                  0.0               -2.444444               0.0            0.408             1.088               1.496       0.048889  0.324436       6.625618                   NaN
1        0.325359    0.44186  0.02568             13                0.0             0.0               7                23.9              0.0                20                0.0                  0.0               -1.466667               0.0            0.884             0.476               1.360       0.044444  0.347858       8.305657                  18.7
2        0.325359    0.44186  0.02568             10                0.0             0.0               4                17.7              0.0                14                0.0                  0.0                0.019048               0.0            0.680             0.272               0.952       0.031111  0.052329       6.199981                  23.9
3        0.325359    0.44186  0.02568             13                0.0             0.0               4                 0.0              0.0                17                0.0                  0.0                0.583333               0.0            0.884             0.272               1.156       0.037778  0.027049       0.376559                  17.7
4        0.325359    0.44186  0.02568             25                0.9             0.0               4                14.3              0.0                29                0.0                  0.0                0.388889               0.0            1.700             0.272               1.972       0.064444  0.255964       5.640034                   0.0

In [59]:
k['Shifted'] =  k['Freight_Total_tonnes'].shift(periods=1)

In [61]:
k = k.drop('Freight_Total_tonnes',axis= 1)

In [63]:
k = k.rename(columns = {'Shifted':'Freight_Total_tonnes'})

In [65]:
airline =k.reset_index(drop=True).dropna()

In [66]:
airline.shape

(4492, 21)

airline.reset_index(drop=True).dropna().head()

In [ ]:
outputCollection = Helpers.createOutputCollection(context)
# out = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=All_airline)
out = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=airline)
# out2 = Helpers.createTemplateOutputDataset(context=context, outputName=outputDataset, dataFrame=All_airline)

outputCollection.addTemplateOutput(out)
Helpers.save(context)